/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-04-28 07:04:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class spdashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Service Provider Dashboard</title>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Orbitron:wght@500&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("    body {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        background: linear-gradient(to bottom right, #0f0f0f, #1a1a1a);\r\n");
      out.write("        font-family: 'Orbitron', sans-serif;\r\n");
      out.write("        color: #00ffee;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    header {\r\n");
      out.write("        background: #000000cc;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        font-size: 2em;\r\n");
      out.write("        text-shadow: 0 0 8px #00ffee;\r\n");
      out.write("        border-bottom: 1px solid #00ffee44;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .dashboard {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        gap: 30px;\r\n");
      out.write("        padding: 60px 20px;\r\n");
      out.write("        flex-wrap: wrap;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card {\r\n");
      out.write("        background: rgba(0, 255, 255, 0.05);\r\n");
      out.write("        border: 1px solid #00ffee55;\r\n");
      out.write("        border-radius: 15px;\r\n");
      out.write("        width: 260px;\r\n");
      out.write("        height: 180px;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        box-shadow: 0 0 20px #00ffee22;\r\n");
      out.write("        transition: transform 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card:hover {\r\n");
      out.write("        transform: translateY(-10px);\r\n");
      out.write("        box-shadow: 0 0 30px #00ffee99;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card a {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: #00ffee;\r\n");
      out.write("        font-size: 1.4em;\r\n");
      out.write("        display: block;\r\n");
      out.write("        margin-top: 40px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card::before {\r\n");
      out.write("        content: '';\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        width: 120%;\r\n");
      out.write("        height: 4px;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        left: -10%;\r\n");
      out.write("        background: linear-gradient(90deg, transparent, #00ffee88, transparent);\r\n");
      out.write("        animation: glowLine 2.5s infinite linear;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @keyframes glowLine {\r\n");
      out.write("        0% { left: -100%; }\r\n");
      out.write("        100% { left: 100%; }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .card-info {\r\n");
      out.write("        font-size: 0.9em;\r\n");
      out.write("        color: #bbffff;\r\n");
      out.write("        margin-top: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    footer {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        color: #888;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header> Service Provider Dashboard</header>\r\n");
      out.write("\r\n");
      out.write("<div class=\"dashboard\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card\" onclick=\"location.href='userRequest.jsp';\">\r\n");
      out.write("        <a href=\"userRequest.jsp\">File Request</a>\r\n");
      out.write("        <div class=\"card-info\">Review and manage file access requests from users in real time.</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card\" onclick=\"location.href='UserDetails.jsp';\">\r\n");
      out.write("        <a href=\"UserDetails.jsp\">User Details</a>\r\n");
      out.write("        <div class=\"card-info\">View registered users, status, and linked file info.</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card\" onclick=\"location.href='index.html';\">\r\n");
      out.write("        <a href=\"index.html\">Logout</a>\r\n");
      out.write("        <div class=\"card-info\">Exit the vault dashboard securely and return to login.</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("    &copy; 2025 | CyberVault Systems - Securing Data with Intelligence\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
