/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-04-28 07:05:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.controller.DAO;
import java.sql.ResultSet;

public final class UserDetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.controller.DAO");
    _jspx_imports_classes.add("java.sql.ResultSet");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>User Details</title>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("    body {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        font-family: 'Montserrat', sans-serif;\r\n");
      out.write("        background: linear-gradient(135deg, #1a1a1a, #0f0f0f);\r\n");
      out.write("        color: #e0f7fa;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    nav {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        margin-bottom: 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    nav a {\r\n");
      out.write("        color: #00e5ff;\r\n");
      out.write("        margin: 0 20px;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        font-size: 1.1em;\r\n");
      out.write("        padding: 10px 15px;\r\n");
      out.write("        border-radius: 6px;\r\n");
      out.write("        transition: background 0.3s, color 0.3s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    nav a:hover {\r\n");
      out.write("        background: #00e5ff33;\r\n");
      out.write("        color: #ffffff;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    h2 {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        color: #00e5ff;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("        text-shadow: 0 0 10px #00e5ff88;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    table {\r\n");
      out.write("        width: 90%;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("        border-collapse: collapse;\r\n");
      out.write("        background: #1f1f1f;\r\n");
      out.write("        box-shadow: 0 0 20px #00e5ff22;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    thead {\r\n");
      out.write("        background: #00e5ff;\r\n");
      out.write("        color: #000;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    th, td {\r\n");
      out.write("        padding: 14px 20px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    tbody tr:nth-child(even) {\r\n");
      out.write("        background-color: #2a2a2a;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    tbody tr:hover {\r\n");
      out.write("        background-color: #00e5ff11;\r\n");
      out.write("        transition: background 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    footer {\r\n");
      out.write("        margin-top: 40px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        font-size: 0.9em;\r\n");
      out.write("        color: #888;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav>\r\n");
      out.write("    <a href=\"userRequest.jsp\"> File Request</a>\r\n");
      out.write("    <a href=\"UserDetails.jsp\">User Details</a>\r\n");
      out.write("    <a href=\"index.html\">Logout</a>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<h2> Registered User Details</h2>\r\n");
      out.write("\r\n");
      out.write("<table>\r\n");
      out.write("<thead>\r\n");
      out.write("<tr>\r\n");
      out.write("    <th>User Name</th>\r\n");
      out.write("    <th>Email</th>\r\n");
      out.write("    <th>Mobile</th>\r\n");
      out.write("    <th>Date of Birth</th>\r\n");
      out.write("    <th>Gender</th>\r\n");
      out.write("    <th>Request Time</th>\r\n");
      out.write("</tr>\r\n");
      out.write("</thead>\r\n");
      out.write("<tbody>\r\n");

    /* ResultSet rs = DAO.getpendingdata(); */
    ResultSet rs=DAO.getusers();
    while (rs.next()) {

      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("    <td>");
      out.print( rs.getString(2) );
      out.write("</td>\r\n");
      out.write("    <td>");
      out.print( rs.getString(3) );
      out.write("</td>\r\n");
      out.write("    <td>");
      out.print( rs.getString(5) );
      out.write("</td>\r\n");
      out.write("    <td>");
      out.print( rs.getString(6) );
      out.write("</td>\r\n");
      out.write("    <td>");
      out.print( rs.getString(7) );
      out.write("</td>\r\n");
      out.write("    <td>");
      out.print( rs.getString(9) );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");

    }

      out.write("\r\n");
      out.write("</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("    &copy; 2025 | User Insight Dashboard | Powered by QuantumVault\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
