/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2025-05-26 05:04:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;

public final class fdetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"ISO-8859-1\">\r\n");
      out.write("  <title>File Search Results - SecureCloud</title>\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <style>\r\n");
      out.write("    @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap');\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      font-family: 'Roboto', sans-serif;\r\n");
      out.write("      background: linear-gradient(135deg, #1d4350, #a43931);\r\n");
      out.write("      color: white;\r\n");
      out.write("      padding: 60px 20px;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      flex-direction: column;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    nav {\r\n");
      out.write("      position: fixed;\r\n");
      out.write("      top: 20px;\r\n");
      out.write("      right: 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    nav a {\r\n");
      out.write("      margin-left: 20px;\r\n");
      out.write("      color: #ffffff;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("      font-size: 16px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    nav a:hover {\r\n");
      out.write("      color: #00f0ff;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    h2 {\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      color: #00f0ff;\r\n");
      out.write("      margin-bottom: 40px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .results-container {\r\n");
      out.write("      display: grid;\r\n");
      out.write("      grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));\r\n");
      out.write("      gap: 30px;\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      max-width: 1200px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .result-card {\r\n");
      out.write("      background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("      backdrop-filter: blur(12px);\r\n");
      out.write("      border-radius: 16px;\r\n");
      out.write("      padding: 25px;\r\n");
      out.write("      box-shadow: 0 8px 32px rgba(0,0,0,0.25);\r\n");
      out.write("      transition: transform 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .result-card:hover {\r\n");
      out.write("      transform: translateY(-5px);\r\n");
      out.write("      background: rgba(255, 255, 255, 0.15);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .result-card h3 {\r\n");
      out.write("      color: #00ffe0;\r\n");
      out.write("      margin-bottom: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .result-card p {\r\n");
      out.write("      font-size: 14px;\r\n");
      out.write("      color: #e0f7fa;\r\n");
      out.write("      margin: 8px 0;\r\n");
      out.write("      word-break: break-word;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .request-btn {\r\n");
      out.write("      display: inline-block;\r\n");
      out.write("      margin-top: 15px;\r\n");
      out.write("      padding: 10px 15px;\r\n");
      out.write("      background: #00c6ff;\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("      color: white;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("      transition: background 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .request-btn:hover {\r\n");
      out.write("      background: #009bd1;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media screen and (max-width: 600px) {\r\n");
      out.write("      nav {\r\n");
      out.write("        position: static;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <nav>\r\n");
      out.write("    <a href=\"upload.jsp\">Upload</a>\r\n");
      out.write("    <a href=\"ViewData.jsp\">My Gallery</a>\r\n");
      out.write("    <a href=\"Search.jsp\">Search</a>\r\n");
      out.write("    <a href=\"viewkey.jsp\">View Key</a>\r\n");
      out.write("    <a href=\"logout\">Logout</a>\r\n");
      out.write("  </nav>\r\n");
      out.write("\r\n");
      out.write("  <h2>Search Results</h2>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"results-container\">\r\n");
      out.write("    ");

      ResultSet rs = (ResultSet) request.getAttribute("result");
      String userid = (String) session.getAttribute("user");
      while (rs != null && rs.next()) {
    
      out.write("\r\n");
      out.write("      <div class=\"result-card\">\r\n");
      out.write("    File Name:    <h3>");
      out.print( rs.getString(2) );
      out.write("</h3> <!-- File Name -->\r\n");
      out.write("        <p><strong>Encrypted Data:</strong> <h3>");
      out.print( rs.getString(5) );
      out.write("</h3></p>\r\n");
      out.write("        <p><strong>User ID:</strong> <h3>");
      out.print( rs.getString(7) );
      out.write("</h3></p>\r\n");
      out.write("        <a class=\"request-btn\" href=\"request.jsp?Id=");
      out.print( rs.getInt(1) );
      out.write("&&userId=");
      out.print( userid );
      out.write("&&FName=");
      out.print( rs.getString(2) );
      out.write("\">Request Access</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    ");

      }
    
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
