/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2025-05-26 04:47:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <title>SecureCloud Login</title>\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <style>\r\n");
      out.write("    @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap');\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      font-family: 'Roboto', sans-serif;\r\n");
      out.write("      background: linear-gradient(135deg, #0f2027, #203a43, #2c5364);\r\n");
      out.write("      height: 100vh;\r\n");
      out.write("      overflow-x: hidden;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      flex-direction: column;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      justify-content: flex-start;\r\n");
      out.write("      padding: 60px 20px 20px;\r\n");
      out.write("      color: white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    nav {\r\n");
      out.write("      position: fixed;\r\n");
      out.write("      top: 20px;\r\n");
      out.write("      right: 40px;\r\n");
      out.write("      z-index: 10;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    nav a {\r\n");
      out.write("      color: #fff;\r\n");
      out.write("      margin-left: 20px;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("      font-size: 16px;\r\n");
      out.write("      transition: color 0.3s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    nav a:hover {\r\n");
      out.write("      color: #00c6ff;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .info-box {\r\n");
      out.write("      background: rgba(255, 255, 255, 0.15);\r\n");
      out.write("      border-radius: 15px;\r\n");
      out.write("      padding: 25px;\r\n");
      out.write("      margin-bottom: 30px;\r\n");
      out.write("      width: 80%;\r\n");
      out.write("      max-width: 700px;\r\n");
      out.write("      color: #ffffff;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      box-shadow: 0 4px 20px rgba(0,0,0,0.2);\r\n");
      out.write("      backdrop-filter: blur(8px);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .info-box h1 {\r\n");
      out.write("      font-size: 28px;\r\n");
      out.write("      margin-bottom: 10px;\r\n");
      out.write("      color: #00c6ff;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .info-box p {\r\n");
      out.write("      font-size: 16px;\r\n");
      out.write("      line-height: 1.6;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login-container {\r\n");
      out.write("      backdrop-filter: blur(12px);\r\n");
      out.write("      background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("      border-radius: 16px;\r\n");
      out.write("      padding: 40px;\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      max-width: 380px;\r\n");
      out.write("      box-shadow: 0 8px 32px 0 rgba(0,0,0,0.37);\r\n");
      out.write("      color: white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    h2 {\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      margin-bottom: 24px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    input[type=\"email\"],\r\n");
      out.write("    input[type=\"password\"] {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      padding: 10px;\r\n");
      out.write("      margin: 10px 0 20px;\r\n");
      out.write("      border: none;\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("      outline: none;\r\n");
      out.write("      font-size: 16px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    input[type=\"submit\"] {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      padding: 10px;\r\n");
      out.write("      background-color: #00c6ff;\r\n");
      out.write("      border: none;\r\n");
      out.write("      color: white;\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("      font-size: 18px;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("      transition: background 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    input[type=\"submit\"]:hover {\r\n");
      out.write("      background-color: #0072ff;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .error {\r\n");
      out.write("      color: #ff4b5c;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .animated-bg {\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      bottom: -20px;\r\n");
      out.write("      left: 0;\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      height: 45%;\r\n");
      out.write("      background: url('https://www.svgrepo.com/show/494195/cloud-encryption.svg') no-repeat center bottom;\r\n");
      out.write("      background-size: contain;\r\n");
      out.write("      opacity: 0.2;\r\n");
      out.write("      animation: float 8s ease-in-out infinite;\r\n");
      out.write("      pointer-events: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @keyframes float {\r\n");
      out.write("      0%, 100% {\r\n");
      out.write("        transform: translateY(0px);\r\n");
      out.write("      }\r\n");
      out.write("      50% {\r\n");
      out.write("        transform: translateY(-20px);\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media (max-width: 480px) {\r\n");
      out.write("      .info-box h1 {\r\n");
      out.write("        font-size: 22px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .info-box p {\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <nav>\r\n");
      out.write("    <a href=\"SP.jsp\">Service Provider</a>\r\n");
      out.write("    <a href=\"login.jsp\">User Login</a>\r\n");
      out.write("    <a href=\"Register.jsp\">Register</a>\r\n");
      out.write("  </nav>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"info-box\">\r\n");
      out.write("    <h1>Welcome to SecureCloud</h1>\r\n");
      out.write("    <p>SecureCloud is a cutting-edge platform that ensures <strong>safe and efficient data transfer</strong> using <strong>deduplication technology</strong>. \r\n");
      out.write("       By identifying and eliminating redundant data, we reduce storage costs and accelerate transmission-without compromising security.</p>\r\n");
      out.write("    <p>Your trust matters. All data is encrypted and transferred over secure channels.</p>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"login-container\">\r\n");
      out.write("    <h2>User Login</h2>\r\n");
      out.write("    <form action=\"login\" method=\"post\">\r\n");
      out.write("      Email: <input type=\"email\" name=\"email\" required>\r\n");
      out.write("      Password: <input type=\"password\" name=\"password\" required>\r\n");
      out.write("      <input type=\"submit\" value=\"Login\">\r\n");
      out.write("    </form>\r\n");
      out.write("    <p class=\"error\">");
      out.print( request.getAttribute("error") != null ? request.getAttribute("error") : "" );
      out.write("</p>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"animated-bg\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
