/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2025-05-26 04:47:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\r\n");
      out.write("  <title>Register | SecureCloud</title>\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("  <style>\r\n");
      out.write("    * {\r\n");
      out.write("      box-sizing: border-box;\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("      font-family: 'Poppins', sans-serif;\r\n");
      out.write("      background: linear-gradient(120deg, #1f1c2c, #928dab);\r\n");
      out.write("      height: 100vh;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      justify-content: center;\r\n");
      out.write("      overflow: hidden;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      width: 90%;\r\n");
      out.write("      max-width: 1100px;\r\n");
      out.write("      height: 80vh;\r\n");
      out.write("      background: #fff;\r\n");
      out.write("      border-radius: 20px;\r\n");
      out.write("      box-shadow: 0 15px 40px rgba(0, 0, 0, 0.2);\r\n");
      out.write("      overflow: hidden;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .left-panel {\r\n");
      out.write("      flex: 1;\r\n");
      out.write("      background: linear-gradient(to right, #141e30, #243b55);\r\n");
      out.write("      color: white;\r\n");
      out.write("      padding: 60px 40px;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      flex-direction: column;\r\n");
      out.write("      justify-content: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .left-panel h1 {\r\n");
      out.write("      font-size: 36px;\r\n");
      out.write("      margin-bottom: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .left-panel p {\r\n");
      out.write("      font-size: 16px;\r\n");
      out.write("      line-height: 1.6;\r\n");
      out.write("      opacity: 0.9;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-panel {\r\n");
      out.write("      flex: 1.2;\r\n");
      out.write("      padding: 40px 50px;\r\n");
      out.write("      overflow-y: auto;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-panel h2 {\r\n");
      out.write("      font-size: 28px;\r\n");
      out.write("      color: #333;\r\n");
      out.write("      margin-bottom: 25px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-group {\r\n");
      out.write("      position: relative;\r\n");
      out.write("      margin-bottom: 25px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-group input,\r\n");
      out.write("    .form-group select,\r\n");
      out.write("    .form-group textarea {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      padding: 12px;\r\n");
      out.write("      font-size: 15px;\r\n");
      out.write("      border: 1px solid #ccc;\r\n");
      out.write("      border-radius: 8px;\r\n");
      out.write("      background: transparent;\r\n");
      out.write("      color: #333;\r\n");
      out.write("      outline: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-group label {\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: -10px;\r\n");
      out.write("      left: 12px;\r\n");
      out.write("      background: #fff;\r\n");
      out.write("      padding: 0 5px;\r\n");
      out.write("      font-size: 13px;\r\n");
      out.write("      color: #555;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    button {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      padding: 12px;\r\n");
      out.write("      background: #4CAF50;\r\n");
      out.write("      color: white;\r\n");
      out.write("      border: none;\r\n");
      out.write("      border-radius: 8px;\r\n");
      out.write("      font-size: 16px;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("      transition: background 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    button:hover {\r\n");
      out.write("      background: #388e3c;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    nav {\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: 20px;\r\n");
      out.write("      right: 30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    nav a {\r\n");
      out.write("      margin-left: 20px;\r\n");
      out.write("      color: #fff;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      font-weight: 600;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    nav a:hover {\r\n");
      out.write("      text-decoration: underline;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media screen and (max-width: 768px) {\r\n");
      out.write("      .container {\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        height: auto;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .left-panel {\r\n");
      out.write("        padding: 30px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .form-panel {\r\n");
      out.write("        padding: 30px;\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav>\r\n");
      out.write("  <a href=\"SP.jsp\">Service Provider</a>\r\n");
      out.write("  <a href=\"login.jsp\">User Login</a>\r\n");
      out.write("  <a href=\"Register.jsp\">Register</a>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <div class=\"left-panel\">\r\n");
      out.write("    <h1>Welcome to SecureCloud</h1>\r\n");
      out.write("    <p>Join the future of cloud security where deduplication and data integrity meet modern design. Your information is encrypted, efficient, and secure.</p>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"form-panel\">\r\n");
      out.write("    <h2>Create Your Account</h2>\r\n");
      out.write("    <form action=\"Register\" method=\"POST\">\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <label for=\"fullname\">Full Name</label>\r\n");
      out.write("        <input type=\"text\" id=\"fullname\" name=\"fullname\" required>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <label for=\"email\">Email</label>\r\n");
      out.write("        <input type=\"email\" id=\"email\" name=\"email\" required>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <label for=\"password\">Password</label>\r\n");
      out.write("        <input type=\"password\" id=\"password\" name=\"password\" required>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <label for=\"confirm_password\">Confirm Password</label>\r\n");
      out.write("        <input type=\"password\" id=\"confirm_password\" name=\"confirm_password\" required>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <label for=\"phone\">Phone Number</label>\r\n");
      out.write("        <input type=\"tel\" id=\"phone\" name=\"phone\" pattern=\"[0-9]{10}\" placeholder=\"e.g. 9876543210\" required>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <label for=\"dob\">Date of Birth</label>\r\n");
      out.write("        <input type=\"date\" id=\"dob\" name=\"dob\" required>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <label for=\"gender\">Gender</label>\r\n");
      out.write("        <select id=\"gender\" name=\"gender\" required>\r\n");
      out.write("          <option value=\"\">Select Gender</option>\r\n");
      out.write("          <option value=\"Male\">Male</option>\r\n");
      out.write("          <option value=\"Female\">Female</option>\r\n");
      out.write("          <option value=\"Other\">Other</option>\r\n");
      out.write("        </select>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <label for=\"address\">Address</label>\r\n");
      out.write("        <textarea id=\"address\" name=\"address\" rows=\"3\" required></textarea>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <button type=\"submit\">Register</button>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
