/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2025-05-26 04:55:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.controller.DAO;
import java.sql.ResultSet;

public final class userRequest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>User File Requests</title>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write("    body {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        font-family: 'Roboto Mono', monospace;\r\n");
      out.write("        background: #121212;\r\n");
      out.write("        color: #e0f7fa;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    nav {\r\n");
      out.write("        margin-bottom: 30px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    nav a {\r\n");
      out.write("        color: #00e5ff;\r\n");
      out.write("        margin: 0 15px;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        font-size: 1.1em;\r\n");
      out.write("        transition: color 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    nav a:hover {\r\n");
      out.write("        color: #ffffff;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    h2 {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    table {\r\n");
      out.write("        margin: 0 auto;\r\n");
      out.write("        width: 90%;\r\n");
      out.write("        border-collapse: collapse;\r\n");
      out.write("        background: #1e1e1e;\r\n");
      out.write("        box-shadow: 0 0 15px #00e5ff22;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    thead {\r\n");
      out.write("        background: #00e5ff;\r\n");
      out.write("        color: #000;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    th, td {\r\n");
      out.write("        padding: 15px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    tr:nth-child(even) {\r\n");
      out.write("        background-color: #2b2b2b;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    tr:hover {\r\n");
      out.write("        background-color: #00e5ff11;\r\n");
      out.write("        transition: 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .approve-btn {\r\n");
      out.write("        background: #00e5ff;\r\n");
      out.write("        color: #000;\r\n");
      out.write("        padding: 8px 16px;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 6px;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        transition: background 0.3s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .approve-btn:hover {\r\n");
      out.write("        background: #00bcd4;\r\n");
      out.write("        color: #fff;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav>\r\n");
      out.write("    <a href=\"userRequest.jsp\">File Request</a>\r\n");
      out.write("    <a href=\"UserDetails.jsp\">User Details</a>\r\n");
      out.write("    <a href=\"index.html\">Logout</a>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<h2> Pending User File Requests</h2>\r\n");
      out.write("\r\n");
      out.write("<table>\r\n");
      out.write("<thead>\r\n");
      out.write("<tr>\r\n");
      out.write("    <th>FID</th>\r\n");
      out.write("    <th>File Name</th>\r\n");
      out.write("    <th>User ID</th>\r\n");
      out.write("    <th>Status</th>\r\n");
      out.write("</tr>\r\n");
      out.write("</thead>\r\n");
      out.write("<tbody>\r\n");

    ResultSet rs = DAO.getpendingdata();
    while (rs.next()) {

      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("    <td>");
      out.print( rs.getInt(1) );
      out.write("</td>\r\n");
      out.write("    <td>");
      out.print( rs.getString(2) );
      out.write("</td>\r\n");
      out.write("    <td>");
      out.print( rs.getString(3) );
      out.write("</td>\r\n");
      out.write("    <td>\r\n");
      out.write("        <a class=\"approve-btn\" href=\"updatestatus.jsp?Fid=");
      out.print(rs.getInt(1));
      out.write("&Filename=");
      out.print(rs.getString(2));
      out.write("\">Approve</a>\r\n");
      out.write("    </td>\r\n");
      out.write("</tr>\r\n");

    }

      out.write("\r\n");
      out.write("</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
